/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import constant.ServerKonstante;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ilija Dumanović
 */
public class konfiguracijeForma extends javax.swing.JFrame {

    /**
     * Creates new form konfiguracijeForma
     */
    private Properties properties;

    public konfiguracijeForma() {
        initComponents();
        setLocationRelativeTo(null);
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Konfiguracija");

        jLabel1.setText("URL:");

        jLabel2.setText("USERNAME:");

        jLabel3.setText("PASSWORD:");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUrl)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnSave)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        try {
            if (proveraPolja()) {
                String url = txtUrl.getText();
                String username = txtUsername.getText();
                String password = txtPassword.getText();

                properties.put(ServerKonstante.DB_CONFIG_URL, url);
                properties.store(new FileOutputStream(ServerKonstante.FILE_PATH), null);
                properties.put(ServerKonstante.DB_CONFIG_USERNAME, username);
                properties.store(new FileOutputStream(ServerKonstante.FILE_PATH), null);
                properties.put(ServerKonstante.DB_CONFIG_PASSWORD, password);
                properties.store(new FileOutputStream(ServerKonstante.FILE_PATH), null);
                this.dispose();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(konfiguracijeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(konfiguracijeForma.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(konfiguracijeForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private boolean proveraPolja() {
        if (txtUrl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje \"URL\" ne sme biti prazno!");
            return false;
        } else if (txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje \"USERNAME\" ne sme biti prazno!");
            return false;
        } else if (txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Polje \"PASSWORD\" ne sme biti prazno!");
            return false;
        }
        return true;
    }

    private void popuniFormu() {
        try {
            properties = new Properties();
            properties.load(new FileInputStream(ServerKonstante.FILE_PATH));
            txtUrl.setText(properties.getProperty(ServerKonstante.DB_CONFIG_URL));
            txtUsername.setText(properties.getProperty(ServerKonstante.DB_CONFIG_USERNAME));
            txtPassword.setText(properties.getProperty(ServerKonstante.DB_CONFIG_PASSWORD));
        } catch (Exception ex) {
            Logger.getLogger(konfiguracijeForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
