/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import server.Server;

/**
 *
 * @author Ilija Dumanović
 */
public class serverForm extends javax.swing.JFrame {

    /**
     * Creates new form serverForm
     */
    Server server;

    public serverForm() {
        initComponents();
        btnZaustavi.setEnabled(false);
        pnlKorisnici.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPokreni = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        pnlKorisnici = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKorisnici = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokretanje servera");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Server nije pokrenut!");

        btnPokreni.setText("Pokreni server");
        btnPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        jLabel2.setText("Povezani korisnici:");

        tblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKorisnici);

        javax.swing.GroupLayout pnlKorisniciLayout = new javax.swing.GroupLayout(pnlKorisnici);
        pnlKorisnici.setLayout(pnlKorisniciLayout);
        pnlKorisniciLayout.setHorizontalGroup(
            pnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKorisniciLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(550, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKorisniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        pnlKorisniciLayout.setVerticalGroup(
            pnlKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKorisniciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton1.setText("Dodaj novog korsinika");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPokreni)
                        .addGap(68, 68, 68)
                        .addComponent(btnZaustavi)
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPokreni)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(pnlKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniActionPerformed
        server = new Server(this);
        jLabel1.setText("Server je pokrenut!");
        jLabel1.setForeground(Color.green);
        pnlKorisnici.setVisible(true);
        btnZaustavi.setEnabled(true);
        btnPokreni.setEnabled(false);
        tblKorisnici.setModel(new UserTabelModel());
        tblKorisnici.getColumnModel().getColumn(0).setMinWidth(150);
        tblKorisnici.getColumnModel().getColumn(3).setMinWidth(150);
    }//GEN-LAST:event_btnPokreniActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        try {
            if (server.getSS() != null && (server.getSS().isBound())) {
                if (server.vratiListuKorisnika().size() != 0 && server.vratiListuProcesa().size() != 0) {
                    int broj = JOptionPane.showConfirmDialog(this, "Postoji klijent koji je vezan za server. Da li ste sigurni da želite da prekinete konekciju?", "Poruka", JOptionPane.YES_NO_OPTION);
                    if (broj == 0) {
                        server.getSS().close();
                        jLabel1.setText("Server je zaustavljen!");
                        jLabel1.setForeground(Color.red);
                        ((UserTabelModel) tblKorisnici.getModel()).clear();
                        pnlKorisnici.setVisible(false);
                        btnZaustavi.setEnabled(false);
                        btnPokreni.setEnabled(true);

                    }
                } else {
                    server.getSS().close();
                    jLabel1.setText("Server je zaustavljen!");
                    jLabel1.setForeground(Color.red);
                    ((UserTabelModel) tblKorisnici.getModel()).clear();
                    pnlKorisnici.setVisible(false);
                    btnZaustavi.setEnabled(false);
                    btnPokreni.setEnabled(true);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(serverForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new noviKorisnikForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreni;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlKorisnici;
    private javax.swing.JTable tblKorisnici;
    // End of variables declaration//GEN-END:variables

    public JTable getTblKorisnici() {
        return tblKorisnici;
    }
}
